# Generated by Django 4.1.4 on 2022-12-23 14:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_rider_driver_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=80, verbose_name='destination')),
                ('latClient', models.FloatField(default=0.0, verbose_name='lat_client')),
                ('lngClient', models.FloatField(default=0.0, verbose_name='ln_client')),
                ('tripTime', models.DateTimeField(auto_now_add=True, verbose_name='trip_time')),
                ('details', models.CharField(max_length=200, verbose_name='details')),
                ('status', models.IntegerField(default=-1, verbose_name='status')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myApp.driver', verbose_name='driver_id')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myApp.rider', verbose_name='rider_id')),
            ],
        ),
    ]
