# Generated by Django 4.1.4 on 2022-12-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_trip_latdestination_trip_lngdestination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(default=0.0, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lng',
            field=models.FloatField(default=0.0, verbose_name='lng'),
        ),
    ]
