# Generated by Django 4.1.4 on 2023-01-12 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_customuser_lat_customuser_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageStatus', models.IntegerField(default=0, verbose_name='message_status')),
                ('messageData', models.CharField(max_length=200, verbose_name='message_data')),
                ('messageReceiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='message_receiver')),
                ('messageSender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_sender', to=settings.AUTH_USER_MODEL, verbose_name='message_sender')),
                ('tripReference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='myApp.trip', verbose_name='trip_reference')),
            ],
        ),
    ]
